services:
  database:
    image: mysql:8.0
    restart: always
    container_name: payment-system-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DATABASE_PORT}:3306"
    networks:
      - payment-system-network

  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: payment-system-backend
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - database
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${BACKEND_PORT}:9000"
    networks:
      - payment-system-network

  webserver:
    image: nginx:alpine
    container_name: payment-system-webserver
    volumes:
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf
      - ./backend/public:/var/www/html/public:ro
    ports:
      - "${WEBSERVER_PORT}:80"
    depends_on:
      - backend
    networks:
      - payment-system-network

  frontend:
    image: node:20-alpine
    container_name: payment-system-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "${FRONTEND_PORT}:8080"
    command: >
      sh -c "cd /app &&
             npm install -g @quasar/cli &&
             npm install &&
             export NODE_OPTIONS=--dns-result-order=ipv4first &&
             npx quasar dev --host 0.0.0.0 --port 8080"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - API_URL=${API_URL}
    networks:
      - payment-system-network
    restart: always

volumes:
  mysql_data:

networks:
  payment-system-network:
    driver: bridge