version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: payment-backend
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - payment-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=payment_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: payment-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    networks:
      - payment-network
    environment:
      MYSQL_DATABASE: payment_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: payment-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - payment-network
    depends_on:
      - app

  frontend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: payment-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    networks:
      - payment-network
    command: sh -c "npm install && npm run dev"
    depends_on:
      - app

networks:
  payment-network:
    driver: bridge

volumes:
  mysql-data: